// Raw FFI bindings generated by bindgen from libaribcaption's C headers.
// Safe wrappers are provided by the `aribcaption` crate.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}
pub use ffi::*;
